Repository commercetools/nodejs, pull requests merged in 2018-05, with the labels that each got.

#556 Remove `browser` field in `pkg` from all packages
  .flowconfig
  CHANGELOG.md
  docs/sdk/api/sdkMiddlewareAuth.md
  docs/sdk/api/sdkMiddlewareHttp.md
  integration-tests/cli/csv-parser-price.it.js
  integration-tests/cli/discount-codes.it.js
  integration-tests/cli/helpers/utils.js
  integration-tests/package.json
  integration-tests/sdk/auth.it.js
  integration-tests/sdk/channels.it.js
  packages/csv-parser-price/package.json
  packages/csv-parser-price/src/main.js
  packages/csv-parser-state/package.json
  packages/csv-parser-state/src/main.js
  packages/custom-objects-exporter/package.json
  packages/custom-objects-exporter/src/main.js
  packages/discount-code-exporter/package.json
  packages/discount-code-exporter/src/main.js
  packages/discount-code-importer/package.json
  packages/discount-code-importer/src/main.js
  packages/inventories-exporter/package.json
  packages/inventories-exporter/src/main.js
  packages/price-exporter/package.json
  packages/price-exporter/src/main.js
  packages/product-exporter/package.json
  packages/product-exporter/src/main.js
  packages/product-json-to-csv/package.json
  packages/product-json-to-csv/src/main.js
  packages/sdk-middleware-auth/package.json
  packages/sdk-middleware-auth/src/anonymous-session-flow.js
  packages/sdk-middleware-auth/src/base-auth-flow.js
  packages/sdk-middleware-auth/src/client-credentials-flow.js
  packages/sdk-middleware-auth/src/password-flow.js
  packages/sdk-middleware-auth/src/refresh-token-flow.js
  packages/sdk-middleware-auth/test/base-auth-flow.spec.js
  packages/sdk-middleware-http/package.json
  packages/sdk-middleware-http/src/http.js
  packages/sdk-middleware-http/test/http.spec.js
  packages/state-importer/package.json
  packages/state-importer/src/main.js
  types/sdk.js
Labels: Status: Review, Type: Bug

#590 fix(sync-actions): re-order product update actions build sequence
  packages/sync-actions/src/products.js
  packages/sync-actions/test/product-sync-variants.spec.js
  yarn.lock
Labels: Status: Review, Type: Bug

#593 fix(sync-actions/product-types): product types doesn't generate update actions for enum changes
  packages/sync-actions/src/product-types-actions.js
  packages/sync-actions/test/product-types-sync-enums.spec.js
Labels: Type: Bug

#592 feat(sync-actions): configure empty string as not-a-value
  docs/sdk/api/syncActions.md
  packages/sync-actions/src/product-types-actions.js
  packages/sync-actions/src/product-types.js
  packages/sync-actions/src/utils/common-actions.js
  packages/sync-actions/test/product-types-sync-base.spec.js
  types/sdk.js
Labels: Type: New Feature

#602 feat(sync-actions): Add `SyncActionConfig` to all types
  packages/sync-actions/src/cart-discounts-actions.js
  packages/sync-actions/src/cart-discounts.js
  packages/sync-actions/src/categories.js
  packages/sync-actions/src/category-actions.js
  packages/sync-actions/src/customer-actions.js
  packages/sync-actions/src/customer-group-actions.js
  packages/sync-actions/src/customer-group.js
  packages/sync-actions/src/customers.js
  packages/sync-actions/src/discount-codes-actions.js
  packages/sync-actions/src/discount-codes.js
  packages/sync-actions/src/inventories.js
  packages/sync-actions/src/inventory-actions.js
  packages/sync-actions/src/order-actions.js
  packages/sync-actions/src/orders.js
  packages/sync-actions/src/product-actions.js
  packages/sync-actions/src/product-discounts-actions.js
  packages/sync-actions/src/product-discounts.js
  packages/sync-actions/src/product-types.js
  packages/sync-actions/src/products.js
  packages/sync-actions/src/shipping-methods-actions.js
  packages/sync-actions/src/shipping-methods.js
  packages/sync-actions/src/state-actions.js
  packages/sync-actions/src/states.js
  packages/sync-actions/src/tax-categories-actions.js
  packages/sync-actions/src/tax-categories.js
  packages/sync-actions/src/zones-actions.js
  packages/sync-actions/src/zones.js
  packages/sync-actions/test/product-discounts-sync.spec.js
  packages/sync-actions/test/product-types-sync-base.spec.js
  packages/sync-actions/test/shipping-methods.spec.js
  packages/sync-actions/test/states-sync.spec.js
  packages/sync-actions/test/tax-categories-sync.spec.js
  packages/sync-actions/test/utils/common-actions.spec.js
Labels: Type: New Feature
