Repository commercetools/nodejs, pull requests merged in 2018-07, with the labels that each got.

#654 fix(req-builder): ensure that built uri is always the same and defaul…
  docs/sdk/api/apiRequestBuilder.md
  packages/api-request-builder/src/default-params.js
  packages/api-request-builder/src/query-projection.js
  packages/api-request-builder/test/create-service.spec.js
  packages/api-request-builder/test/default-params.spec.js
  packages/api-request-builder/test/query-projection.spec.js
Labels: Status: Review, Type: Breaking Change, Type: Bug

#655 MCD-1236: adding return info actions to order's sync actions
  packages/sync-actions/src/order-actions.js
  packages/sync-actions/src/orders.js
  packages/sync-actions/test/order-sync.spec.js
Labels: Status: Review, Type: Enhancement

#651 feat(custom-objects-importer): add new importer package
  README.md
  docs/SUMMARY.md
  docs/cli/README.md
  docs/cli/custom-objects-importer.md
  integration-tests/cli/__snapshots__/custom-objects-import.it.js.snap
  integration-tests/cli/custom-objects-import.it.js
  integration-tests/package.json
  package.json
  packages/custom-objects-importer/package.json
  packages/custom-objects-importer/readme.md
  packages/custom-objects-importer/src/main.js
  packages/custom-objects-importer/src/utils/silent-logger.js
  packages/custom-objects-importer/test/__snapshots__/main.spec.js.snap
  packages/custom-objects-importer/test/main.spec.js
  types/customObjects.js
  yarn.lock
Labels: Status: Review, Type: New Feature

#668 chore(deps): update dependencies
  .circleci/config.yml
  package.json
Labels: Status: Review, Type: Maintenance

#663 77 clean up flow types
  packages/api-request-builder/src/build-query-string.js
  packages/api-request-builder/src/create-request-builder.js
  packages/api-request-builder/src/create-service.js
  packages/csv-parser-discount-code/src/main.js
  packages/csv-parser-state/src/main.js
  packages/discount-code-exporter/src/main.js
  packages/discount-code-generator/src/main.js
  packages/discount-code-importer/src/main.js
  packages/http-user-agent/src/create-user-agent.js
  packages/inventories-exporter/src/main.js
  packages/personal-data-erasure/src/cli.js
  packages/price-exporter/src/main.js
  packages/product-exporter/src/main.js
  packages/product-json-to-csv/src/main.js
  packages/product-json-to-csv/src/map-product-data.js
  packages/sdk-client/src/client.js
  packages/sdk-middleware-auth/src/anonymous-session-flow.js
  packages/sdk-middleware-auth/src/base-auth-flow.js
  packages/sdk-middleware-auth/src/client-credentials-flow.js
  packages/sdk-middleware-auth/src/existing-token.js
  packages/sdk-middleware-auth/src/password-flow.js
  packages/sdk-middleware-auth/src/refresh-token-flow.js
  packages/sdk-middleware-correlation-id/src/correlation-id.js
  packages/sdk-middleware-http/src/http.js
  packages/sdk-middleware-logger/src/logger.js
  packages/sdk-middleware-logger/test/logger.spec.js
  packages/sdk-middleware-queue/src/queue.js
  packages/sdk-middleware-user-agent/src/user-agent.js
  packages/state-importer/src/main.js
  packages/sync-actions/src/states.js
  types/discountCodes.js
  types/sdk.js
  types/state.js
Labels: Status: Review, Type: Maintenance, Type: Onboarding Task

#670 chore(docs): add 'todo' cmd and auto generate todo docs
  README.md
  TODOS.md
  lint-staged.config.js
  package.json
  packages/custom-objects-importer/src/main.js
  yarn.lock
Labels: Type: Question

#672 chore(renovate): pin all dependencies
  .renovaterc.json
Labels: Type: Maintenance

#678 chore(deps): update dependencies
  .circleci/config.yml
  package.json
Labels: Status: Review, Type: Maintenance

#673 Add set valid from and until action for discounts
  packages/sync-actions/src/cart-discounts.js
  packages/sync-actions/src/discount-codes.js
  packages/sync-actions/src/product-discounts.js
  packages/sync-actions/src/utils/combine-validity-actions.js
  packages/sync-actions/test/cart-discounts-sync.spec.js
  packages/sync-actions/test/discount-codes-sync.spec.js
  packages/sync-actions/test/product-discounts-sync.spec.js
  packages/sync-actions/test/utils/combine-validity-actions.spec.js
Labels: Status: Review, Type: New Feature

#686 chore(deps): dependencies update of node 6 & 8 docker digests, flow-b…
  .circleci/config.yml
  package.json
Labels: Status: Review, Type: Maintenance
