Repository commercetools/nodejs, pull requests merged in 2018-08, with the labels that each got.

#693 chore(deps): dependencies update of circleci
  .circleci/config.yml
Labels: Status: Review, Type: Maintenance

#695 fix(product-json-to-csv): fix not shown zero value in csv export
  .flowconfig
  packages/product-json-to-csv/src/map-headers.js
  packages/product-json-to-csv/src/map-product-data.js
  packages/product-json-to-csv/test/__snapshots__/map-product-data.spec.js.snap
  packages/product-json-to-csv/test/map-headers.spec.js
  packages/product-json-to-csv/test/map-product-data.spec.js
  yarn.lock
Labels: Status: Review, Type: Bug

#698 chore(deps): update dependencies of circleci node
  .circleci/config.yml
Labels: Status: Review, Type: Maintenance

#701 Add channels syncer to sync actions package
  TODOS.md
  docs/sdk/api/syncActions.md
  packages/sync-actions/src/channels-actions.js
  packages/sync-actions/src/channels.js
  packages/sync-actions/src/index.js
  packages/sync-actions/test/channels-sync-.spec.js
Labels: Type: Enhancement, Type: New Feature

#707 chore(deps): update dependencies
  .circleci/config.yml
  package.json
Labels: Status: Review, Type: Maintenance

#708 docs(contributing.md): update docs on integration test
  CONTRIBUTING.md
  TODOS.md
Labels: Status: Review, Type: Maintenance

#716 chore(deps): update dependencies of circleci/node
  .circleci/config.yml
Labels: Status: Review, Type: Maintenance

#731 chore(tooling): pin deps when publishing instead of using ranges
  lerna.json
Labels: Type: Enhancement, Type: Maintenance
