Repository commercetools/nodejs, pull requests merged in 2018-09, with the labels that each got.

#754 chore(renovate): remove limitation of concurrent pull requests
  .renovaterc.json
Labels: Type: Maintenance

#792 chore(deps): Update dependencies passed test from renovate
  .circleci/config.yml
  integration-tests/package.json
  package.json
  packages/csv-parser-discount-code/package.json
  packages/csv-parser-price/package.json
  packages/custom-objects-importer/package.json
  packages/discount-code-exporter/package.json
  packages/discount-code-generator/package.json
  packages/personal-data-erasure/package.json
  packages/product-json-to-csv/package.json
Labels: Status: Review, Type: Maintenance

#789 refactor(sync-actions/product-types): apply hints for nested value changes.
  docs/sdk/api/syncActions.md
  package.json
  packages/sync-actions/src/product-types-actions.js
  packages/sync-actions/src/product-types.js
  packages/sync-actions/src/utils/common-actions.js
  packages/sync-actions/src/utils/create-build-actions.js
  packages/sync-actions/test/__snapshots__/product-types-sync-attribute-hints.spec.js.snap
  packages/sync-actions/test/product-types-sync-attribute-hints.spec.js
  packages/sync-actions/test/product-types-sync-attributes.spec.js
  packages/sync-actions/test/product-types-sync-base.spec.js
  packages/sync-actions/test/product-types-sync-enums.spec.js
  yarn.lock
Labels: Status: Review, Type: Breaking Change

#811 [sync-actions] improve sync actions module
  packages/sync-actions/src/utils/create-build-actions.js
  packages/sync-actions/test/product-sync-prices.spec.js
Labels: Status: Review

#816 chore(deps): successful dependencies update without breaking change
  .circleci/config.yml
  package.json
  packages/csv-parser-orders/package.json
  packages/discount-code-importer/package.json
  packages/price-exporter/package.json
  packages/product-json-to-csv/package.json
  yarn.lock
Labels: Status: Review, Type: Maintenance

#833 chore: update deps
  .circleci/config.yml
  package.json
  packages/csv-parser-state/package.json
  packages/custom-objects-exporter/package.json
  packages/customer-groups-exporter/package.json
  packages/discount-code-importer/package.json
  packages/personal-data-erasure/package.json
  packages/product-exporter/package.json
  packages/product-json-to-csv/package.json
  packages/product-json-to-xlsx/package.json
  packages/sync-actions/package.json
  yarn.lock
Labels: Type: Maintenance

#836 (sync-actions): support custom fields updates in orders
  packages/sync-actions/src/orders.js
  packages/sync-actions/test/order-sync.spec.js
Labels: Type: Enhancement
