Repository commercetools/nodejs, pull requests merged in 2018-10, with the labels that each got.

#867 chore(deps): dependencies update
  .circleci/config.yml
  .flowconfig
  package.json
  packages/csv-parser-orders/package.json
  packages/csv-parser-price/package.json
  packages/csv-parser-state/package.json
  packages/custom-objects-exporter/package.json
  packages/customer-groups-exporter/package.json
  packages/get-credentials/package.json
  packages/personal-data-erasure/package.json
  packages/product-exporter/package.json
  packages/product-json-to-csv/package.json
  packages/product-json-to-xlsx/package.json
  yarn.lock
Labels: Status: Review, Type: Maintenance

#892 Add support to sync projects
  docs/sdk/api/syncActions.md
  packages/sync-actions/src/index.js
  packages/sync-actions/src/projects-actions.js
  packages/sync-actions/src/projects.js
  packages/sync-actions/test/projects-sync.spec.js
Labels: Type: Enhancement

#869 fix(product-json-to-csv): handle conflicting attribute names
  TODOS.md
  packages/product-json-to-csv/src/map-product-data.js
  packages/product-json-to-csv/src/writer.js
  packages/product-json-to-csv/test/__snapshots__/map-product-data.spec.js.snap
  packages/product-json-to-csv/test/__snapshots__/writer.spec.js.snap
  packages/product-json-to-csv/test/map-product-data.spec.js
  packages/product-json-to-csv/test/writer.spec.js
  packages/product-json-to-xlsx/src/writer.js
  packages/product-json-to-xlsx/test/__snapshots__/writer.spec.js.snap
  packages/product-json-to-xlsx/test/writer.spec.js
Labels: Status: Review

#894 feat(category-exporter): add new exporter package
  docs/SUMMARY.md
  docs/cli/category-exporter.md
  integration-tests/cli/__snapshots__/category-exporter.it.js.snap
  integration-tests/cli/category-exporter.it.js
  integration-tests/cli/helpers/category-export.data.js
  integration-tests/package.json
  packages/category-exporter/bin/category-exporter.js
  packages/category-exporter/package.json
  packages/category-exporter/src/cli.js
  packages/category-exporter/src/main.js
  packages/category-exporter/src/utils/silent-logger.js
  packages/category-exporter/test/main.spec.js
  types/categoryExporter.js
  yarn.lock
Labels: Status: Review, Type: New Feature

#908 chore(lerna): update bootstrap command
  lerna.json
Labels: Type: Maintenance

#904 fix(docs): add category-exporter docs
  README.md
  docs/cli/README.md
  packages/category-exporter/readme.md
Labels: Status: Review, Type: Documentation

#914 feat(sdk-auth): add several new features to sdkAuth module
  docs/sdk/api/sdkAuth.md
  integration-tests/sdk/auth.it.js
  packages/sdk-auth/package.json
  packages/sdk-auth/src/auth.js
  packages/sdk-auth/test/client-password-flow.spec.js
  packages/sdk-auth/test/common.spec.js
  packages/sdk-auth/test/custom-flow.spec.js
  packages/sdk-auth/test/customer-password-flow.spec.js
  types/sdk.js
  yarn.lock
Labels: Type: Enhancement

#935 chore(deps): dependencies update
  .circleci/config.yml
  .flowconfig
  package.json
  packages/category-exporter/package.json
  packages/csv-parser-discount-code/package.json
  packages/csv-parser-orders/package.json
  packages/csv-parser-price/package.json
  packages/csv-parser-state/package.json
  packages/custom-objects-exporter/package.json
  packages/customer-groups-exporter/package.json
  packages/discount-code-generator/package.json
  packages/get-credentials/package.json
  packages/personal-data-erasure/package.json
  packages/product-exporter/package.json
  packages/product-json-to-csv/package.json
  packages/product-json-to-xlsx/package.json
  packages/sdk-auth/package.json
  yarn.lock
Labels: Status: Review, Type: Maintenance

#933 feat(sdk-auth): add a possibility to specify a custom authType and token
  docs/sdk/api/sdkAuth.md
  packages/sdk-auth/src/auth.js
  packages/sdk-auth/src/constants.js
  packages/sdk-auth/test/common.spec.js
  packages/sdk-auth/test/custom-flow.spec.js
  types/sdk.js
Labels: Status: Review

#934 Add support of withTotal to api-request-builder
  docs/sdk/api/apiRequestBuilder.md
  packages/api-request-builder/src/build-query-string.js
  packages/api-request-builder/src/default-params.js
  packages/api-request-builder/src/query-page.js
  packages/api-request-builder/test/build-query-string.spec.js
  packages/api-request-builder/test/default-params.spec.js
  packages/api-request-builder/test/query-page.spec.js
  types/sdk.js
Labels: Type: New Feature
