Repository commercetools/nodejs, pull requests merged in 2018-03, with the labels that each got.

#481 feat(auth-middleware): add middleware for existing token
  docs/cli/product-exporter.md
  docs/sdk/Middlewares.md
  docs/sdk/api/README.md
  docs/sdk/api/sdkMiddlewareAuth.md
  packages/sdk-middleware-auth/src/existing-token.js
  packages/sdk-middleware-auth/src/index.js
  packages/sdk-middleware-auth/test/existing-token.spec.js
  types/sdk.js
Labels: Status: Review, Type: Enhancement

#482 fix(zones-locations): fix zone locations updates
  packages/sync-actions/src/zones-actions.js
  packages/sync-actions/test/zones.spec.js
Labels: Status: Review, Type: Bug

#436 feat(shipping-methods-sync-actions): Add sync actions for Shipping Methods
  docs/sdk/api/syncActions.md
  packages/sync-actions/src/index.js
  packages/sync-actions/src/shipping-methods-actions.js
  packages/sync-actions/src/shipping-methods.js
  packages/sync-actions/test/shipping-methods.spec.js
Labels: Type: Enhancement

#484 chore(github-template): update issue template
  .github/issue_template.md
Labels: Status: Review, Type: Maintenance

#485 feat(sdk-middleware-http): allow to pass credentials mode to fetch object
  docs/sdk/api/sdkMiddlewareHttp.md
  packages/sdk-middleware-http/src/http.js
  types/sdk.js
Labels: Status: Review, Type: New Feature

#486 fix(sync-action): setDescription -> changeDescription
  packages/sync-actions/src/product-types-actions.js
  packages/sync-actions/test/product-types-sync-base.spec.js
Labels: Status: Review, Type: Bug

#495 feat(sync-actions): add state update actions
  docs/sdk/api/syncActions.md
  packages/sync-actions/src/index.js
  packages/sync-actions/src/state-actions.js
  packages/sync-actions/src/states.js
  packages/sync-actions/src/utils/create-build-array-actions.js
  packages/sync-actions/test/states-sync.spec.js
Labels: Status: Review, Type: New Feature

#504 feat(state-importer): add new state importer package
  CONTRIBUTING.md
  README.md
  docs/SUMMARY.md
  docs/cli/README.md
  docs/cli/state-importer.md
  integration-tests/cli/state-import.it.js
  integration-tests/package.json
  packages/state-importer/package.json
  packages/state-importer/readme.md
  packages/state-importer/src/main.js
  packages/state-importer/test/helpers/sampleStates.json
  packages/state-importer/test/main.spec.js
  types/state.js
  yarn.lock
Labels: Status: Review, Type: New Feature

#517 fix(tax-categories-actions): Fix issue when doing multiple complex actions on rates
  packages/sync-actions/src/tax-categories-actions.js
  packages/sync-actions/test/tax-categories-sync.spec.js
Labels: Status: Review, Type: Bug
