Repository commercetools/nodejs, pull requests merged in 2018-06, with the labels that each got.

#621 chore(deps): update dependencies
  .circleci/config.yml
  package.json
  yarn.lock
Labels: Status: Review, Type: Maintenance

#622 docs(docs): fix typo's in docs
  docs/sdk/api/README.md
  docs/sdk/api/sdkMiddlewareAuth.md
  docs/sdk/api/sdkMiddlewareHttp.md
  docs/sdk/api/sdkMiddlewareLogger.md
  docs/sdk/api/sdkMiddlewareQueue.md
  docs/sdk/api/sdkMiddlewareUserAgent.md
Labels: Status: Review, Type: Documentation, Type: Maintenance, Type: Onboarding Task

#630 chore(deps): dependencies updates docker digest, flow-bin and eslint…
  .circleci/config.yml
  package.json
Labels: Status: Review, Type: Maintenance

#631 docs(product-json-to-csv): Set correct link in readme
  packages/product-json-to-csv/readme.md
Labels: Status: Review, Type: Documentation, Type: Maintenance, Type: Onboarding Task

#637 chore(deps): update dependencies
  .circleci/config.yml
  package.json
Labels: Status: Review, Type: Maintenance

#647 perf(deps): remove bluebird dependency
  packages/csv-parser-price/package.json
  packages/discount-code-importer/package.json
  packages/discount-code-importer/src/main.js
  packages/price-exporter/package.json
  packages/price-exporter/src/main.js
  packages/state-importer/package.json
  packages/state-importer/src/main.js
Labels: Status: Review, Type: Enhancement
