Repository commercetools/nodejs, pull requests merged in 2018-02, with the labels that each got.

#445 chore(deps): update dependencies in bulk
  package.json
  packages/sdk-middleware-auth/package.json
  packages/sdk-middleware-http/package.json
  yarn.lock
Labels: Status: Review, Type: Maintenance

#448 feat(api-request-builder): add password token and password reset
  packages/api-request-builder/src/default-services.js
  packages/api-request-builder/test/create-request-builder.spec.js
Labels: Type: New Feature

#437 fix(zone-actions): refactor actions mapping for locations
  packages/sync-actions/src/zones-actions.js
  packages/sync-actions/src/zones.js
  packages/sync-actions/test/zones.spec.js
Labels: Type: Bug

#418 332 prod json csv cli
  .babelrc
  integration-tests/cli/helpers/product-headers.csv
  integration-tests/cli/helpers/product-json2csv.data.js
  integration-tests/cli/helpers/products-to-parse.json
  integration-tests/cli/helpers/utils.js
  integration-tests/cli/product-json-to-csv.it.js
  integration-tests/package.json
  package.json
  packages/product-json-to-csv/bin/product-json-to-csv.js
  packages/product-json-to-csv/package-lock.json
  packages/product-json-to-csv/package.json
  packages/product-json-to-csv/src/cli.js
  packages/product-json-to-csv/src/main.js
  packages/product-json-to-csv/src/map-headers.js
  packages/product-json-to-csv/src/map-product-data.js
  packages/product-json-to-csv/test/main.spec.js
  packages/product-json-to-csv/test/map-headers.spec.js
  types/product.js
  yarn.lock
Labels: Status: Review, Type: New Feature

#452 chore(api-request-builder): add update, del and create as implicit features
  packages/api-request-builder/src/default-services.js
  packages/api-request-builder/src/features.js
  packages/api-request-builder/test/exports.spec.js
Labels: Type: Bug, Type: Documentation

#450 feat(api-request-builder): add email and password features
  packages/api-request-builder/src/default-services.js
  packages/api-request-builder/test/create-request-builder.spec.js
Labels: Type: New Feature

#453 docs(license): add a license file
  LICENSE
Labels: Status: Review, Type: Documentation, Type: Enhancement, Type: Spike

#456 446 docs update
  docs/SUMMARY.md
  docs/cli/csv-parser-discount-code.md
  docs/cli/csv-parser-orders.md
  docs/cli/csv-parser-price.md
  docs/cli/discount-code-exporter.md
  docs/cli/discount-code-generator.md
  docs/cli/discount-code-importer.md
  docs/cli/inventories-exporter.md
  docs/cli/price-exporter.md
  docs/cli/product-exporter.md
  docs/sdk/Middlewares.md
  docs/sdk/api/sdkMiddlewareAuth.md
Labels: Status: Review, Type: Documentation

#465 chore(dependencies): update renovate dependencies in bulk
  package.json
  yarn.lock
Labels: Status: Review, Type: Maintenance

#454 Docs/json2csv
  README.md
  docs/SUMMARY.md
  docs/cli/README.md
  docs/cli/product-exporter.md
  docs/cli/product-json-to-csv.md
  yarn.lock
Labels: Status: Review, Type: Documentation

#467 feat(sync-actions): add `extract-matching-pairs`
  packages/sync-actions/src/product-actions.js
  packages/sync-actions/src/utils/extract-matching-pairs.js
  packages/sync-actions/test/utils/extract-matching-pairs.spec.js
Labels: Type: Enhancement

#469 431 code groups csv parser
  packages/csv-parser-discount-code/package.json
  packages/csv-parser-discount-code/src/index.js
  packages/csv-parser-discount-code/src/main.js
  packages/csv-parser-discount-code/test/main.spec.js
Labels: Status: Review

#470 sync-actions: add product-types
  docs/sdk/api/syncActions.md
  packages/sync-actions/package.json
  packages/sync-actions/src/index.js
  packages/sync-actions/src/product-types-actions.js
  packages/sync-actions/src/product-types.js
  packages/sync-actions/test/product-types-sync-attributes.spec.js
  packages/sync-actions/test/product-types-sync-base.spec.js
  packages/sync-actions/test/product-types-sync-enums.spec.js
Labels: Type: New Feature

#478 chore(deps): update dpendencies from renovate
  package.json
  packages/csv-parser-discount-code/test/main.spec.js
  packages/csv-parser-orders/test/deliveries.spec.js
  packages/csv-parser-price/test/main.spec.js
  packages/csv-parser-price/test/map-custom-fields.spec.js
  packages/discount-code-generator/test/main.spec.js
  packages/discount-code-importer/src/index.js
  packages/discount-code-importer/test/main.spec.js
  packages/sdk-middleware-auth/package.json
  packages/sdk-middleware-http/package.json
  yarn.lock
Labels: Type: Maintenance

#480 fix(http-user-agent): remove eval in favor of CSP compliant browser detection
  packages/http-user-agent/src/create-user-agent.js
  packages/http-user-agent/test/create-user-agent.spec.js
Labels: Status: Review, Type: Bug
