Repository commercetools/nodejs, pull requests merged in 2019-01, with the labels that each got.

#1063 chore(deps): update deps
  .circleci/config.yml
  package.json
  packages/category-exporter/package.json
  packages/csv-parser-state/package.json
  packages/custom-objects-exporter/package.json
  packages/customer-groups-exporter/package.json
  packages/personal-data-erasure/package.json
  packages/product-exporter/package.json
  packages/product-json-to-csv/package.json
  packages/product-json-to-xlsx/package.json
  packages/sdk-auth/package.json
  packages/sdk-middleware-auth/package.json
  packages/sdk-middleware-http/package.json
  yarn.lock
Labels: Status: In Progress, Type: Maintenance

#1085 chore: add keyword for automation
  integration-tests/cli/__snapshots__/category-exporter.it.js.snap
  integration-tests/cli/__snapshots__/csv-parser-price.it.js.snap
  integration-tests/cli/__snapshots__/custom-objects-export.it.js.snap
  integration-tests/cli/__snapshots__/customer-groups-export.it.js.snap
  integration-tests/cli/__snapshots__/inventories-exporter.it.js.snap
  integration-tests/cli/__snapshots__/price-export.it.js.snap
  integration-tests/cli/__snapshots__/product-export.it.js.snap
  integration-tests/cli/__snapshots__/product-json-to-csv.it.js.snap
  integration-tests/cli/__snapshots__/product-json-to-xlsx.it.js.snap
  packages/category-exporter/package.json
  packages/csv-parser-discount-code/package.json
  packages/csv-parser-discount-code/src/cli.js
  packages/csv-parser-orders/package.json
  packages/csv-parser-price/package.json
  packages/csv-parser-price/src/cli.js
  packages/csv-parser-state/package.json
  packages/custom-objects-exporter/package.json
  packages/customer-groups-exporter/package.json
  packages/discount-code-exporter/package.json
  packages/discount-code-generator/package.json
  packages/inventories-exporter/package.json
  packages/price-exporter/package.json
  packages/product-exporter/package.json
  packages/product-json-to-csv/package.json
  packages/product-json-to-xlsx/package.json
Labels: Type: New Feature

#1100 chore(deps): deps update
  .circleci/config.yml
  .flowconfig
  package.json
  packages/category-exporter/package.json
  packages/csv-parser-orders/package.json
  packages/csv-parser-price/package.json
  packages/csv-parser-state/package.json
  packages/custom-objects-exporter/package.json
  packages/customer-groups-exporter/package.json
  packages/get-credentials/package.json
  packages/personal-data-erasure/package.json
  packages/product-exporter/package.json
  packages/product-json-to-csv/package.json
  packages/product-json-to-xlsx/package.json
  yarn.lock
Labels: Node SDK, Status: Review, Type: Maintenance

#1116 chore(deps): deps update
  .circleci/config.yml
  integration-tests/sdk/channels.it.js
  package.json
  packages/category-exporter/package.json
  packages/csv-parser-state/package.json
  packages/custom-objects-exporter/package.json
  packages/customer-groups-exporter/package.json
  packages/personal-data-erasure/package.json
  packages/product-exporter/package.json
  packages/product-json-to-csv/package.json
  packages/product-json-to-xlsx/package.json
  packages/sync-actions/package.json
  yarn.lock
Labels: Node SDK, Status: Review, Type: Bug, Type: Maintenance
