Repository commercetools/nodejs, pull requests merged in 2019-03, with the labels that each got.

#1168 feat(product-json-to-csv): add customerGroup to product prices
  integration-tests/cli/helpers/product-json2csv.data.js
  integration-tests/cli/product-json-to-csv.it.js
  packages/product-json-to-csv/src/main.js
  packages/product-json-to-csv/src/map-product-data.js
  packages/product-json-to-csv/test/main.spec.js
  types/product.js
Labels: Status: Review

#1167 feat(): add support for head method on sdk middleware http
  packages/sdk-middleware-http/src/http.js
  packages/sdk-middleware-http/test/http.spec.js
Labels: Status: Review, Type: Enhancement

#1194 chore(deps): deps update
  .circleci/config.yml
  .flowconfig
  .nvmrc
  package.json
  packages/csv-parser-orders/package.json
  packages/csv-parser-price/package.json
  packages/get-credentials/package.json
  packages/resource-deleter/package.json
  yarn.lock
Labels: Type: Maintenance

#1202 chore(deps): deps update
  .circleci/config.yml
  .nvmrc
  package.json
  yarn.lock
Labels: Status: Review, Type: Maintenance

#1204 test(auth.it.js): Fix failing auth integration test
  integration-tests/sdk/auth.it.js
Labels: Status: Review, Type: Bug

#1215 chore(deps): Deps update
  .circleci/config.yml
  .flowconfig
  integration-tests/package.json
  package.json
  packages/custom-objects-importer/package.json
  packages/get-credentials/package.json
  packages/resource-deleter/package.json
  yarn.lock
Labels: Type: Maintenance

#1228 chore(deps): deps update
  .circleci/config.yml
  package.json
  packages/csv-parser-orders/package.json
  packages/csv-parser-price/package.json
  packages/get-credentials/package.json
  packages/resource-deleter/package.json
  yarn.lock
Labels: Type: Maintenance
