Repository commercetools/nodejs, pull requests merged in 2019-02, with the labels that each got.

#1130 chore(deps): deps update
  .circleci/config.yml
  .flowconfig
  .nvmrc
  package.json
  yarn.lock
Labels: Node SDK, Type: Maintenance

#1132 docs(): fix broken query predicate docs link
  docs/cli/category-exporter.md
  docs/cli/custom-objects-exporter.md
  docs/cli/customer-groups-exporter.md
  docs/cli/discount-code-exporter.md
  docs/cli/price-exporter.md
  docs/cli/product-exporter.md
Labels: Status: Review, Type: Bug

#1140 chore(deps): deps update
  .flowconfig
  package.json
  yarn.lock
Labels: Status: Review, Type: Maintenance

#1134 fix(): unused global variables error
  packages/sdk-auth/src/auth.js
  packages/sdk-middleware-http/src/http.js
Labels: Status: Review, Type: Bug

#1141 fix(): only pin devDependencies
  .prettierignore
  .renovaterc.json
  integration-tests/package.json
  packages/category-exporter/package.json
  packages/csv-parser-discount-code/package.json
  packages/csv-parser-orders/package.json
  packages/csv-parser-price/package.json
  packages/csv-parser-state/package.json
  packages/custom-objects-exporter/package.json
  packages/custom-objects-importer/package.json
  packages/customer-groups-exporter/package.json
  packages/discount-code-exporter/package.json
  packages/discount-code-generator/package.json
  packages/discount-code-importer/package.json
  packages/get-credentials/package.json
  packages/inventories-exporter/package.json
  packages/personal-data-erasure/package.json
  packages/price-exporter/package.json
  packages/product-exporter/package.json
  packages/product-json-to-csv/package.json
  packages/product-json-to-xlsx/package.json
  packages/sdk-auth/package.json
  packages/sdk-middleware-auth/package.json
  packages/sdk-middleware-user-agent/package.json
  packages/state-importer/package.json
  packages/sync-actions/package.json
  yarn.lock
Labels: Status: Review

#1156 chore(deps): deps update
  .flowconfig
  package.json
  packages/category-exporter/package.json
  packages/csv-parser-discount-code/package.json
  packages/csv-parser-orders/package.json
  packages/csv-parser-price/package.json
  packages/csv-parser-state/package.json
  packages/custom-objects-exporter/package.json
  packages/customer-groups-exporter/package.json
  packages/discount-code-exporter/package.json
  packages/discount-code-generator/package.json
  packages/inventories-exporter/package.json
  packages/personal-data-erasure/package.json
  packages/price-exporter/package.json
  packages/product-exporter/package.json
  packages/product-json-to-csv/package.json
  packages/product-json-to-xlsx/package.json
  yarn.lock
Labels: Status: Review, Type: Maintenance

#1165 chore(deps): deps update
  .circleci/config.yml
  package.json
  packages/csv-parser-orders/package.json
  packages/csv-parser-price/package.json
  packages/get-credentials/package.json
  yarn.lock
Labels: Node SDK, Type: Maintenance

#1143 fix(deps): stop Lerna using exact versions
  lerna.json
  packages/category-exporter/package.json
  packages/csv-parser-price/package.json
  packages/csv-parser-state/package.json
  packages/custom-objects-exporter/package.json
  packages/custom-objects-importer/package.json
  packages/customer-groups-exporter/package.json
  packages/discount-code-exporter/package.json
  packages/discount-code-importer/package.json
  packages/inventories-exporter/package.json
  packages/personal-data-erasure/package.json
  packages/price-exporter/package.json
  packages/product-exporter/package.json
  packages/product-json-to-csv/package.json
  packages/product-json-to-xlsx/package.json
  packages/sdk-auth/package.json
  packages/state-importer/package.json
Labels: Status: Review

#985 feat(resource-deleter): new resource deleter package
  README.md
  docs/SUMMARY.md
  docs/cli/README.md
  docs/cli/resource-deleter.md
  integration-tests/cli/__snapshots__/resource-deleter.it.js.snap
  integration-tests/cli/helpers/resource-delete.data.js
  integration-tests/cli/resource-deleter.it.js
  integration-tests/package.json
  packages/resource-deleter/bin/resource-deleter.js
  packages/resource-deleter/package.json
  packages/resource-deleter/readme.md
  packages/resource-deleter/src/cli.js
  packages/resource-deleter/src/constants.js
  packages/resource-deleter/src/main.js
  packages/resource-deleter/src/utils/silent-logger.js
  packages/resource-deleter/test/main.spec.js
  types/resourceDeleter.js
  yarn.lock
Labels: Status: Review, Type: New Feature
