Repository commercetools/nodejs, pull requests merged in 2019-04, with the labels that each got.

#1238 chore(deps): deps update
  .circleci/config.yml
  integration-tests/package.json
  package.json
  packages/csv-parser-discount-code/package.json
  packages/csv-parser-orders/package.json
  packages/csv-parser-price/package.json
  packages/get-credentials/package.json
  packages/product-json-to-csv/package.json
  packages/product-json-to-xlsx/package.json
  packages/resource-deleter/package.json
  yarn.lock
Labels: Type: Maintenance

#1242 fix: add locale action in customer sync actions
  packages/sync-actions/src/customer-actions.js
  packages/sync-actions/test/customer-sync.spec.js
Labels: Status: Review

#1239 fix(sync-actions): customer resourceId undefined error
  packages/sync-actions/src/utils/common-actions.js
  packages/sync-actions/test/customer-sync.spec.js
Labels: Status: Review, Type: Bug

#1250 chore: update deps
  .circleci/config.yml
  .flowconfig
  package.json
  yarn.lock
Labels: Status: Review

#1266 chore(deps): deps update
  .circleci/config.yml
  .flowconfig
  package.json
  packages/resource-deleter/package.json
  yarn.lock
Labels: Type: Maintenance

#1276 chore: update deps
  .circleci/config.yml
  package.json
  packages/csv-parser-orders/package.json
  packages/csv-parser-price/package.json
  packages/get-credentials/package.json
Labels: Status: Review

#1277 feat(inventories-exporter): add a possibility to export predefined fields
  docs/cli/inventories-exporter.md
  integration-tests/cli/__snapshots__/inventories-exporter.it.js.snap
  packages/inventories-exporter/src/cli.js
  packages/inventories-exporter/src/main.js
  packages/inventories-exporter/test/main.spec.js
  types/inventory.js
Labels: Status: Review

#1278 1268 inventory exporter export with template fix
  packages/inventories-exporter/src/cli.js
Labels: Status: Review

#1290 chore: update deps
  .circleci/config.yml
  .flowconfig
  package.json
  packages/category-exporter/package.json
  packages/resource-deleter/package.json
  packages/sdk-auth/package.json
  packages/sdk-middleware-http/package.json
  yarn.lock
Labels: Status: Review

#1269 feat(sync-actions): Add a support for changeAttributeOrderByName action
  packages/sync-actions/src/product-types-actions.js
  packages/sync-actions/src/product-types.js
  packages/sync-actions/test/product-types-sync-base.spec.js
Labels: Status: Review
