Repository commercetools/nodejs, pull requests merged in 2019-09, with the labels that each got.

#1392 feat(sync-actions): add setSalutation to customer sync
  packages/sync-actions/src/customer-actions.js
  packages/sync-actions/test/customer-sync.spec.js
Labels: Minor, Node SDK, Status: Review, Type: New Feature

#1412 Add sync actions to stores
  docs/sdk/api/syncActions.md
  packages/sync-actions/src/index.js
  packages/sync-actions/src/stores-actions.js
  packages/sync-actions/src/stores.js
  packages/sync-actions/test/stores-sync.spec.js
Labels: Type: New Feature

#1413 chore(package.json): deps installed
  TODOS.md
  package.json
Labels: Status: Review, Type: Maintenance
