Repository commercetools/nodejs, pull requests merged in 2019-05, with the labels that each got.

#1294 fix(exporters): enable request retries
  packages/category-exporter/src/main.js
  packages/custom-objects-exporter/src/main.js
  packages/customer-groups-exporter/src/main.js
  packages/discount-code-exporter/src/main.js
  packages/inventories-exporter/src/main.js
  packages/price-exporter/src/main.js
  packages/product-exporter/src/main.js
Labels: Status: Review

#1307 chore(deps): deps update
  .circleci/config.yml
  integration-tests/package.json
  package.json
  packages/get-credentials/package.json
  packages/sdk-auth/package.json
  packages/sdk-middleware-http/package.json
  packages/sync-actions/package.json
  yarn.lock
Labels: Type: Maintenance

#1311 docs: update readme with support link
  README.md
Labels: Status: Review

#1319 chore(deps): deps update
  .circleci/config.yml
  .flowconfig
  package.json
  yarn.lock
Labels: Type: Maintenance

#1321 chore(renovate): automerge all non major updates and enable emergency…
  .renovaterc.json
Labels: Status: Review

#1326 chore(deps): deps update
  .circleci/config.yml
  package.json
  yarn.lock
Labels: Type: Maintenance

#1329 feat(api-request-builder): add orderEdits endpoint to sdk
  TODOS.md
  packages/api-request-builder/src/build-query-string.js
  packages/api-request-builder/src/create-request-builder.js
  packages/api-request-builder/src/create-service.js
  packages/api-request-builder/src/default-params.js
  packages/api-request-builder/src/default-services.js
  packages/api-request-builder/src/order-edit-apply.js
  packages/api-request-builder/test/create-request-builder.spec.js
  packages/api-request-builder/test/create-service.spec.js
  types/sdk.js
  yarn.lock
Labels: Type: New Feature
