Repository commercetools/nodejs, pull requests merged in 2020-03, with the labels that each got.

#1496 feat(product-exporter): add productTypeKey column while exporting
  packages/product-json-to-csv/src/map-product-data.js
  types/product.js
Labels: Status: Review

#1501 feat(sync-actions): add localized description for shipping methods
  packages/sync-actions/src/shipping-methods-actions.js
  packages/sync-actions/test/shipping-methods.spec.js
Labels: Minor, Node SDK, Status: Review, Type: New Feature

#1505 fix(sync-actions): bug where we throw on empty assets in categories
  .flowconfig
  packages/sync-actions/src/categories.js
  packages/sync-actions/src/utils/copy-empty-array-props.js
  packages/sync-actions/test/category-sync.spec.js
Labels: Type: Bug
