Repository commercetools/nodejs, pull requests merged in 2020-04, with the labels that each got.

#1514 feat(sync-actions): add set key actions
  packages/sync-actions/src/customer-actions.js
  packages/sync-actions/src/product-discounts-actions.js
  packages/sync-actions/src/zones-actions.js
  packages/sync-actions/test/cart-discounts-sync.spec.js
  packages/sync-actions/test/customer-sync.spec.js
  packages/sync-actions/test/product-discounts-sync.spec.js
  packages/sync-actions/test/zones.spec.js
Labels: Type: New Feature

#1515 feat(request-builder): add orderNumber support on order service
  packages/api-request-builder/src/create-service.js
  packages/api-request-builder/src/default-params.js
  packages/api-request-builder/src/query-id.js
  packages/api-request-builder/test/create-service.spec.js
  packages/api-request-builder/test/query-id.spec.js
  types/sdk.js
Labels: Minor, Type: New Feature

#1521 fix(default-services): change wrong endpoints
  packages/api-request-builder/src/default-services.js
Labels: Type: Bug

#1522 feat(api-request-builder): adding stores to the package
  packages/api-request-builder/src/default-services.js
  packages/api-request-builder/test/create-request-builder.spec.js
Labels: Type: New Feature

#1524 refactor(api-request-builder): rename createService argument
  packages/api-request-builder/src/create-service.js
Labels: Type: Enhancement

#1525 fix(sync-actions): copy empty array props for products and variants
  packages/sync-actions/src/products.js
  packages/sync-actions/src/utils/copy-empty-array-props.js
  packages/sync-actions/test/product-sync-variants.spec.js
  packages/sync-actions/test/utils/copy-empty-array-props.spec.js
Labels: Type: Bug

#1530 feat(sync-actions/stores): add `setDistributionChannels`
  packages/sync-actions/src/stores-actions.js
  packages/sync-actions/test/stores-sync.spec.js
Labels: Status: Review, Type: Enhancement

#1532 Adnasa null check copy array props
  packages/sync-actions/src/utils/copy-empty-array-props.js
  packages/sync-actions/test/utils/copy-empty-array-props.spec.js
Labels: Type: Bug

#1543 feat(SyncActions): Add CustomType actions in inventory entries
  packages/sync-actions/src/customers.js
  packages/sync-actions/src/inventories.js
  packages/sync-actions/test/inventory-sync.spec.js
Labels: Type: New Feature
