Repository commercetools/nodejs, pull requests merged in 2020-01, with the labels that each got.

#1455 fix(ts-sdk): handling of undefined parameter
  packages/typescript-sdk/src/generated/base/requests-utils.ts
  yarn.lock
Labels: Type: Bug

#1457 chore: regenerate lockfile
  yarn.lock
Labels: Type: Maintenance

#1461 feat(product): add support for dimensions in image url
  .flowconfig
  packages/product-json-to-csv/src/map-product-data.js
  packages/product-json-to-csv/test/__snapshots__/map-product-data.spec.js.snap
Labels: Type: New Feature

#1468 feat(sync/customers): add `setStores`
  packages/sync-actions/src/customer-actions.js
  packages/sync-actions/test/customer-sync.spec.js
Labels: Status: Review
