Repository commercetools/nodejs, pull requests merged in 2020-06, with the labels that each got.

#1562 fix(sync-actions): generate PriceCustom actions before changePrice
  packages/sync-actions/src/products.js
  packages/sync-actions/test/product-sync-prices.spec.js
Labels: Type: Bug

#1571 feat(sync-actions/stores): add set supply channels
  packages/sync-actions/src/stores-actions.js
  packages/sync-actions/test/stores-sync.spec.js
Labels: Type: New Feature, Type: adnasa is king 👑

#1572 chore: update emails commercetools.de -> commercetools.com
  packages/category-exporter/package.json
  packages/csv-parser-state/package.json
  packages/custom-objects-exporter/package.json
  packages/custom-objects-importer/package.json
  packages/customer-groups-exporter/package.json
  packages/inventories-exporter/package.json
  packages/personal-data-erasure/package.json
  packages/price-exporter/package.json
  packages/product-exporter/package.json
  packages/product-json-to-csv/package.json
  packages/product-json-to-xlsx/package.json
  packages/resource-deleter/package.json
  packages/state-importer/package.json
Labels: Minor, Status: Review, Type: Maintenance
