Repository commercetools/nodejs, pull requests merged in 2021-03, with the labels that each got.

#1654 fix(sdk-middleware-http): try json parse with catch block
  integration-tests/cli/helpers/personal-data-erasure.data.js
  integration-tests/cli/personal-data-erasure.it.js
  packages/sdk-middleware-http/src/http.js
  packages/sdk-middleware-http/test/http.spec.js
Labels: Type: Bug

#1662 fix(sync-actions): changing order of actions
  packages/sync-actions/src/product-actions.js
  packages/sync-actions/src/products.js
  packages/sync-actions/test/product-sync-images.spec.js
  packages/sync-actions/test/product-sync-variants.spec.js
Labels: Type: Bug

#1664 feat(sync-actions): add sync actions for assets
  packages/sync-actions/src/product-actions.js
  packages/sync-actions/src/utils/action-map-custom.js
  packages/sync-actions/test/product-sync-variants.spec.js
Labels: Type: New Feature

#1668 1667 personal data eraser timeout with sorting
  packages/personal-data-erasure/src/main.js
  packages/personal-data-erasure/test/main.spec.js
Labels: Type: Bug, Type: New Feature
