Repository commercetools/nodejs, pull requests merged in 2023-05, with the labels that each got.

#1852 BMU-401 fix(sync-actions): fix type sync-actions errors
  .changeset/rich-taxis-shake.md
  packages/sync-actions/src/types-actions.js
  packages/sync-actions/test/types-sync-fields.spec.js
Labels: Type: Bug

#1853 BMU-401 feat(sync-actions): type entity, support new actions
  .changeset/rich-taxis-shake.md
  packages/sync-actions/src/types-actions.js
  packages/sync-actions/test/types-sync-enums.spec.js
  packages/sync-actions/test/types-sync-fields.spec.js
Labels: Type: New Feature

#1856 [PANGOLIN-2857]: Support changes on delivery items (`setDeliveryItems`)
  .changeset/afraid-eels-sleep.md
  packages/sync-actions/src/order-actions.js
  packages/sync-actions/src/orders.js
  packages/sync-actions/test/order-sync.spec.js
Labels: Minor
